name: 构建Windows可执行文件

on:
  release:
    types: [created]  # 当创建release时触发
  workflow_dispatch:    # 允许手动触发工作流
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.11']
    permissions:
      contents: write  # 需要写入权限以上传到release
      packages: read
    
    defaults:
      run:
        working-directory: report_generator  # 设置默认工作目录
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: 缓存Python依赖
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: 缓存PyInstaller
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pyinstaller
        key: ${{ runner.os }}-pyinstaller-${{ hashFiles('**/ReportGenX.py') }}
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller Pillow --no-cache-dir
        
    - name: 使用PyInstaller打包
      run: |
        pyinstaller.exe -F -i resources\icon\favicon.ico -w ReportGenX.py

    - name: 复制必要文件
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "dist/conf","dist/data","dist/resources/icon","dist/resources/templates"
        robocopy . dist /E /XD .git build __pycache__ /XF *.pyc *.pyo *.pyd /NFL /NDL /NJH /NJS /nc /ns /np
        exit 0
    
    - name: 压缩构建产物
      working-directory: report_generator/dist  # 覆盖默认工作目录
      run: |
        7z a -mx=1 -mmt=on ReportGenX.zip ReportGenX.exe conf data resources

    - name: 清理构建产物
      working-directory: report_generator/dist  # 覆盖默认工作目录
      shell: pwsh
      run: |
        Remove-Item -Path "build" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "conf" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "data" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "resources" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "ReportGenX.exe" -Force -ErrorAction SilentlyContinue

    - name: 上传构建产物到Artifacts
      if: github.event_name == 'workflow_dispatch'  # 仅在手动触发时执行
      uses: actions/upload-artifact@v4
      with:
        name: ReportGenX
        path: report_generator/dist/ReportGenX.zip

    - name: 上传Release资产
      if: github.event_name == 'release'  # 仅在release触发时执行
      uses: softprops/action-gh-release@v1
      with:
        files: report_generator/dist/ReportGenX.zip