name: 构建Windows可执行文件

on:
  push:
    branches: [ main ]  # 当推送到main分支时触发
  pull_request:
    branches: [ main ]  # 当对main分支发起PR时触发
  workflow_dispatch:    # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest  # 在Windows环境中运行
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # 使用与您开发环境相同的Python版本
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
        pip install pyinstaller
        
    - name: 使用PyInstaller打包
      run: |
        pyinstaller.exe -F -i resources\icon\favicon.ico -w ReportGenX.py
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: ReportGenX
        path: dist/ReportGenX.exe
